### ISSUE TITLE
allow for multiple dropdowns

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/dynamicGrammars#2]
the tool current relies on the id field to know what to change. this prevents us from having two dropdowns on the same page at once

https://github.com/Barnard-PL-Labs/dynamicGrammars/blob/84bfd69b967832e95e93fad965a399302209ff3a/frontEnd/tsl.js#L26

**Comment by ravenrothkopf** [comment]
Fixed! Now able to add multiple dropdowns with the press of a button
