### ISSUE TITLE
add comments

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/dynamicGrammars#25]
What is toSE and toTE?

https://github.com/Barnard-PL-Labs/dynamicGrammars/blob/fae8bb278b500ee4598e87708212c16ebe4c84be/frontEnd/dropdownsForAPI.js#L66

**Comment by LeyiCui-Angel** [comment]
toSE: switch to the structured editor
toTE: switch to the text editor, update the content of text editor according to the structured editor
Comments added.
