### ISSUE TITLE
Extract plain text file of user's constructed TSL for exportation

### ISSUE THREAD

**Issue by ravenrothkopf** [Barnard-PL-Labs/dynamicGrammars#7]
May have to reformat data collection into an AST to do so, try using console.log() first.

**Comment by ravenrothkopf** [comment]
Getting there! I wrote an extract function w/ a button that console.logs the plain text version of the specifications (without spacing, I don't know if that's an issue?). Now just need to figure out how to export console output...

**Comment by santolucito** [comment]
awesome! 

we will use this export eventually to send the spec to a synthesis api, but you are right, it would be nice to export as a plaintext file just in case someone wants to run synthesis locally. Maybe this could work for downloading the text version to the client? https://stackoverflow.com/a/30832210/1609406

**Comment by ravenrothkopf** [comment]
Yeah that totally worked, thank you! A bit clunky, but it gets the job done for now.

**Comment by santolucito** [comment]
lgtm!
