### ISSUE TITLE
Can't select first item of dropdown to add to LTL or TSL line

### ISSUE THREAD

**Issue by ravenrothkopf** [Barnard-PL-Labs/dynamicGrammars#8]
I'm not sure if this happened during the program simplification, but I'll look into it!

**Comment by santolucito** [comment]
can you explain the steps to reproduce this error? I am not seeing on my end

**Comment by ravenrothkopf** [comment]
Let's say I create a new dropdown and navigate to the "atom" selector. Once I'm there, I'm unable to select "b" which is the top dropdown option, I can only select "a". If this is just an error on my end let me know and I'll close the issue!

**Comment by ravenrothkopf** [comment]
Upon further inspection, this seems to only happen when I'm on the Safari browser? Weird.
